/* eslint-disable no-console */
/**
 * Generates `src/config.js` the same way ElectionDashboard does.
 *
 * Source project reference:
 * - /home/onexys/abss/projects/election/ElectionDashboard/generate-env.js
 *
 * This script reads from environment variables (preferred), and falls back to
 * the ElectionDashboard "test" defaults if nothing is provided.
 *
 * Run:
 *   node generate-env.js
 */

const fs = require("fs");

const DEFAULTS = {
  // Defaults copied from ElectionDashboard/src/config.js
  AWS_REGION: "eu-central-1",
  USER_POOL_ID: "eu-central-1_thYUuQRxo",
  USER_POOL_CLIENT_ID: "50cdhcakes9ijt1i450kuoieab",
  IDENTITY_POOL_ID: "eu-central-1:b13921c6-c843-46de-af4b-c1a557fbb950",
  API_NAME: "test-election-client-api",
  API_URL: "https://yt3rfcbzxa.execute-api.eu-central-1.amazonaws.com/test",
  BUCKET: "",
};

function env(name) {
  return process.env[name] && String(process.env[name]).trim();
}

// Prefer Expo public env vars (so they work with Expo dev server)
const apiName = env("EXPO_PUBLIC_AMPLIFY_API_NAME") || env("API_NAME") || DEFAULTS.API_NAME;
const apiUrl = env("EXPO_PUBLIC_AMPLIFY_API_URL") || env("API_URL") || DEFAULTS.API_URL;

const userPoolId =
  env("EXPO_PUBLIC_COGNITO_USER_POOL_ID") || env("USER_POOL_ID") || DEFAULTS.USER_POOL_ID;
const userPoolClientId =
  env("EXPO_PUBLIC_COGNITO_USER_POOL_CLIENT_ID") ||
  env("USER_POOL_CLIENT_ID") ||
  DEFAULTS.USER_POOL_CLIENT_ID;
const identityPoolId =
  env("EXPO_PUBLIC_COGNITO_IDENTITY_POOL_ID") || env("IDENTITY_POOL_ID") || DEFAULTS.IDENTITY_POOL_ID;

const region =
  env("EXPO_PUBLIC_AWS_REGION") ||
  env("AWS_REGION") ||
  (userPoolId.includes("_") ? userPoolId.split("_")[0] : DEFAULTS.AWS_REGION);

const bucket = env("EXPO_PUBLIC_S3_BUCKET") || env("BUCKET") || DEFAULTS.BUCKET;

const configFile = `// THIS FILE IS AUTO-GENERATED by \`node generate-env.js\`
// Do not edit manually. Update env vars and re-run the generator.

export const AMPLIFY_API = {
  region: '${region}',
  userPoolId: '${userPoolId}',
  userPoolClientId: '${userPoolClientId}',
  apiName: '${apiName}',
  apiURL: '${apiUrl}',
  identityPoolId: '${identityPoolId}',
  bucket: '${bucket}',
};
`;

fs.mkdirSync("src", { recursive: true });
fs.writeFileSync("src/config.js", configFile, "utf8");
console.log("Wrote src/config.js");

