// THIS FILE IS AUTO-GENERATED by `node generate-env.js`
// Do not edit manually. Update env vars and re-run the generator.

export const AMPLIFY_API = {
  region: 'eu-central-1',
  userPoolId: 'eu-central-1_thYUuQRxo',
  userPoolClientId: '50cdhcakes9ijt1i450kuoieab',
  apiName: 'test-election-client-api',
  apiURL: 'https://yt3rfcbzxa.execute-api.eu-central-1.amazonaws.com/test',
  identityPoolId: 'eu-central-1:b13921c6-c843-46de-af4b-c1a557fbb950',
  bucket: '',
};
